### ISSUE TITLE
Fleeing fox

### ISSUE THREAD

**Issue by Daelyx** [TalonFloof/Vulpine#1]
Hi ! I love your mod, but it seems that it causes wild foxes to flee even when sneaking, which makes it very hard... When I disable Vulpine, they behave normally, so it's definitely the cause ; also I noticed that foxes coming from spawn eggs don't flee at all, even in survival.

**Comment by TalonFloof** [comment]
Interesting, I'll take a look at that

**Comment by TalonFloof** [comment]
After looking at the code, this is actually intentional. If the foxes aren't running from you in vanilla minecraft, then that should be a bug with the game since they are supposed to run according to Minecraft's source code.

**Comment by Daelyx** [comment]
Ah, no in vanilla they are supposed to run, except if you're sneaking ; that's how you get to breed them

**Comment by TalonFloof** [comment]
oop my bad, let me fix this real quick

**Comment by TalonFloof** [comment]
fixed, i'll release it on modrinth shortly

**Comment by Daelyx** [comment]
Amazing, thank you for the quick response :)
